from ruby
run apt-get update
run apt-get install -y nodejs
run gem install rails
run mkdir /webapp
add . /webapp
workdir webapp
run bundle install
run RAILS_ENV=production bundle exec rake assets:precompile
CMD ["rails", "server", "-b", "0.0.0.0"]